# Generated by Django 6.0.1 on 2026-01-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryIntro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='7:22', max_length=100)),
                ('opening_note', models.TextField(help_text='The very first text she sees before opening the diary.')),
                ('wax_seal_color', models.CharField(default='#8b0000', help_text='HEX color for the wax seal.', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DiaryPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField(help_text='The order of the page. 1 is the cover/first page.', unique=True)),
                ('photo', models.ImageField(help_text='Upload a high-quality picture of her.', upload_to='memories/')),
                ('message', models.TextField(help_text='Write your romantic 1600s style message here.')),
                ('question', models.CharField(default='Shall we proceed, my love?', help_text="The question above the 'YES' button.", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['page_number'],
            },
        ),
    ]
