# Generated by Django 6.0.1 on 2026-01-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diarypage',
            name='chapter_title',
            field=models.CharField(default='A New Chapter', help_text="The title displayed under 'The Queen in Motion'.", max_length=200),
        ),
    ]
