# Generated by Django 6.0.1 on 2026-01-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_diarypage_chapter_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='diarypage',
            name='is_finale',
            field=models.BooleanField(default=False, help_text='Check this ONLY for the last page (the collage page).'),
        ),
    ]
