# Generated by Django 6.0.1 on 2026-01-21 12:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_diarypage_is_finale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarypage',
            name='photo',
            field=cloudinary.models.CloudinaryField(help_text='Upload a high-quality picture of her.', max_length=255, verbose_name='image'),
        ),
    ]
